# NumPy
<li>NumPy stands for <b>Numerical Python</b>.</li>
<li>NumPy is the fundamental packages for scientific computing in Python.</li>
<li>It is a Python library which provides support for large, multi-dimensional arrays and matrices.</li>
<li>It also provides support for a large collection of high-level mathematical functions to operate on these arrays and matrices.</li>


## Importance Of NumPy In Python

<li>support for wide variety of mathematical operation on arrays and matrices.</li>
<li>provides various functions for searching, sorting, performing statistical operations and other basic linear algebric operations.</li>

## Installation Of NumPy
<li>Go to your terminal, open and activate your virtual environment and then use the following commands for installing numpy.</li>
<code>
    pip install numpy
</code>


## Importing NumPy
<li>We need to import numpy if we want to create any numpy arrays and perform any operations on them.</li>
<li>We can import numpy package using the following command:</li>
<code>
import numpy as np
</code>

In [1]:
import numpy as np

## Creating Numpy Arrays.

<li>We can create a numpy array by using the function np.array()</li>
<li>Inside the np.array() method, we pass a list of items or a list of list of items.</li>

In [2]:
numpy_array = np.array([1,2,3,4])

In [3]:
print(numpy_array)

[1 2 3 4]


In [5]:
print(type(numpy_array))

<class 'numpy.ndarray'>


In [4]:
a = [1,2,3,4]
print(a)

[1, 2, 3, 4]


In [6]:
print(type(a))

<class 'list'>


In [7]:
list_of_list = [['Ram', 'Thapa', 22], ['Shyam', 'Thapa', 32]]

In [8]:
twod_array = np.array(list_of_list)
print(twod_array)

[['Ram' 'Thapa' '22']
 ['Shyam' 'Thapa' '32']]


In [9]:
print(type(twod_array))

<class 'numpy.ndarray'>


### Question

<li>Import numpy, and assign it to the alias np.</li>
<li>Create a NumPy ndarray from the list [10, 20, 30]. Assign the result to the variable data_ndarray</li>

In [10]:
import numpy as np

In [11]:
data_ndarray = np.array([10,20,30])

In [12]:
print(data_ndarray)

[10 20 30]


In [13]:
print(type(data_ndarray))

<class 'numpy.ndarray'>


## NumPy Vs Python Lists
<li>Importing module</li>
<li>Numerical Operations.</li>
<li>consumes less memory.</li>
<li>fast as compared to the python itselt.</li>
<li>convenient to use.</li>

## Comparing Numpy With Python Lists

<li><b>Size/Memory:</b>Numpy array takes less space than that of Python lists.</li>
<li><b>Speed/Performance:</b>It takes less time in Numpy array to compute the same task than that of Python lists.</li>

### Memory Comparision Between NumPy & Python Lists
<li>For doing the memory comparision, we have getsizeof() function which can be imported from sys library.</li>
<li>We can create a list and numpy array containing the same elements and check their size and compare them.</li>


In [14]:
from sys import getsizeof

In [25]:
x_list = [i for i in range(1000000)]
size_xlist = getsizeof(x_list)
print(size_xlist)

8697456


In [26]:
x_array = np.array(x_list)
size_xarray = getsizeof(x_array)
print(size_xarray)

4000112


In [29]:
print("NumPy array takes {} times less space than that of Python list".format(size_xlist / size_xarray))

NumPy array takes 2.1743031195126536 times less space than that of Python list


### Speed Comparision Between NumPy Array & Python List
<li>For doing the speed comparision, we have to perform same operation with Python list and NumPy arrays.</li>
<li>We can calculate the time taken by each operation and then compare their speed or performance.</li>
<li>For doing this, we have a time module(library) from which we can calculate the start_time using time.process_time().</li>
<li>Similarly, we can also calculate the end_time using the same time.process_time().</li>
<li>Here start_time means time before performing operation and end_time mens time after performing operation.</li>
<li>This way, we can calculate the time taken by the operation by using end_time - start_time formula.</li>
<li>Finally, we can compare both times and see which is faster.</li>

In [30]:
first_list = [i for i in range(1, 100000000)]

In [31]:
print(type(first_list))

<class 'list'>


In [32]:
first_ndarray = np.array(first_list)

In [33]:
print(type(first_ndarray))

<class 'numpy.ndarray'>


In [34]:
import time

In [35]:
start_time = time.perf_counter()
sum_first_list = sum(first_list)
end_time = time.perf_counter()
list_processing_time = end_time - start_time
print(list_processing_time)

1.7313156000000163


In [36]:
start_time = time.perf_counter()
sum_first_array = np.sum(first_ndarray)
end_time = time.perf_counter()
ndarray_processing_time = end_time - start_time
print(ndarray_processing_time)

0.05772589999992306


In [37]:
print("Operations On NumPy is {} time faster than that of Python list".format(list_processing_time/ndarray_processing_time))

Operations On NumPy is 29.992007054066267 time faster than that of Python list


## Dimensions In Arrays
<li>You can get the number of dimensions, shape (length of each dimension), and size (number of all elements) of the NumPy array with ndim, shape, and size attributes of numpy.ndarray.</li>
<li>The built-in function len() returns the size of the first dimension.</li>
<li>Number of dimensions of the NumPy array: ndim</li>
<li>Shape of the NumPy array: shape</li>
<li>Size of the NumPy array: size</li>
<li>Size of the first dimension of the NumPy array: len()</li>

<ol>
    <li><b>One Dimensional Arrays:</b> If an array has only one dimension then it is one dimensional array.</li>
    <li><b>Two Dimensional Arrays:</b> If an array has two dimensions along x and y axis then it is two dimensional arrays.</li>
    <li><b>Three Dimensional Arrays:</b> If an array has three dimensions along x, y and z axis then it is three dimensional arrays.</li>
    <li><b>Higher(N) Dimensional Arrays:</b> If an array has more than three dimensions then such arrays are called n-dimensional  or higher dimensional arrays.</li>
</ol>

In [38]:
onedarray = np.array([1,2,3,4])

In [39]:
onedarray.ndim

1

In [45]:
onedarray.shape

(4,)

In [47]:
onedarray.size

4

In [46]:
len(onedarray)

4

In [48]:
twodarray = np.array([[1,2,3,4], [5,6,7,8]])

In [49]:
print(twodarray)

[[1 2 3 4]
 [5 6 7 8]]


In [50]:
twodarray.ndim

2

In [51]:
twodarray.size

8

In [52]:
twodarray.shape

(2, 4)

In [53]:
len(twodarray)

2

In [54]:
threedarray = np.array([[[1, 2, 3], [4, 5, 6]]])

In [55]:
threedarray.ndim

3

In [56]:
threedarray.shape

(1, 2, 3)

In [57]:
threedarray.size

6

In [58]:
len(threedarray)

1

In [59]:
threedarray2 = np.array([[[1,2,3], [4,5,6]], [[9,8,7], [6,5,4]]])

In [62]:
print(threedarray2)

[[[1 2 3]
  [4 5 6]]

 [[9 8 7]
  [6 5 4]]]


In [60]:
threedarray2.ndim

3

In [61]:
threedarray2.shape

(2, 2, 3)

In [63]:
threedarray2.size

12

In [64]:
len(threedarray2)

2

In [67]:
fourdarray = np.array([[[[1,2,3,4], [4,3,2,1]]], [[[5,6,7,8], [8,7,6,5]]]])

In [71]:
print(fourdarray)

[[[[1 2 3 4]
   [4 3 2 1]]]


 [[[5 6 7 8]
   [8 7 6 5]]]]


In [72]:
fourdarray.ndim

4

In [73]:
fourdarray.shape

(2, 1, 2, 4)

In [74]:
fourdarray.size

16

In [75]:
len(fourdarray)

2

In [76]:
fivedarray = np.array([1,2,3,4], ndmin = 5)

In [77]:
fivedarray

array([[[[[1, 2, 3, 4]]]]])

In [79]:
fivedarray.ndim

5

In [80]:
fivedarray.shape

(1, 1, 1, 1, 4)

In [81]:
fivedarray.size

4

### Question
<li><b>Read the car_details.csv file using csv reader, convert them into lists of lists and then create a numpy array using the lists of list.</b></li>

In [82]:
from csv import reader
file = open('car_details.csv')
file_read = reader(file)
data = list(file_read)

In [83]:
print(data[1:6])

[['Maruti 800 AC', '2007', '60000', '70000', 'Petrol', 'Individual', 'Manual', 'First Owner'], ['Maruti Wagon R LXI Minor', '2007', '135000', '50000', 'Petrol', 'Individual', 'Manual', 'First Owner'], ['Hyundai Verna 1.6 SX', '2012', '600000', '100000', 'Diesel', 'Individual', 'Manual', 'First Owner'], ['Datsun RediGO T Option', '2017', '250000', '46000', 'Petrol', 'Individual', 'Manual', 'First Owner'], ['Honda Amaze VX i-DTEC', '2014', '450000', '141000', 'Diesel', 'Individual', 'Manual', 'Second Owner']]


In [84]:
csv_array = np.array(data[1:])
print(csv_array)

[['Maruti 800 AC' '2007' '60000' ... 'Individual' 'Manual' 'First Owner']
 ['Maruti Wagon R LXI Minor' '2007' '135000' ... 'Individual' 'Manual'
  'First Owner']
 ['Hyundai Verna 1.6 SX' '2012' '600000' ... 'Individual' 'Manual'
  'First Owner']
 ...
 ['Maruti 800 AC BSIII' '2009' '110000' ... 'Individual' 'Manual'
  'Second Owner']
 ['Hyundai Creta 1.6 CRDi SX Option' '2016' '865000' ... 'Individual'
  'Manual' 'First Owner']
 ['Renault KWID RXT' '2016' '225000' ... 'Individual' 'Manual'
  'First Owner']]


In [85]:
print(csv_array.ndim)

2


In [86]:
print(csv_array.shape)

(4340, 8)


In [87]:
print(csv_array.size)

34720


In [88]:
print(len(csv_array))

4340


## Special NumPy Arrays

<ol>
    <li><b>np.zeros():</b>The zeros() function is used to get a new array of given shape and type, filled with zeros.</li>
    <li><b>np.ones():</b>The ones() function is used to get a new array of given shape and type, filled with ones.</li>
</ol>

In [89]:
zeros_array = np.zeros(4)
print(zeros_array)
print(zeros_array.ndim)
print(zeros_array.shape)
print(zeros_array.size)

[0. 0. 0. 0.]
1
(4,)
4


In [91]:
zeros_array2d = np.zeros((3,5))
print(zeros_array2d)
print(zeros_array2d.ndim)
print(zeros_array2d.shape)
print(zeros_array2d.size)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
2
(3, 5)
15


In [92]:
zeros_array3d = np.zeros((3,5,2))
print(zeros_array3d)
print(zeros_array3d.ndim)
print(zeros_array3d.shape)
print(zeros_array3d.size)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
3
(3, 5, 2)
30


In [93]:
zeros_array2d = np.zeros((3,5), dtype = 'int')
print(zeros_array2d)
print(zeros_array2d.ndim)
print(zeros_array2d.shape)
print(zeros_array2d.size)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
2
(3, 5)
15


In [94]:
ones_array = np.ones(4)
print(ones_array)
print(ones_array.ndim)
print(ones_array.shape)
print(ones_array.size)
print(len(ones_array))

[1. 1. 1. 1.]
1
(4,)
4
4


In [95]:
ones_array_2d = np.ones((4, 5))
print(ones_array_2d)
print(ones_array_2d.ndim)
print(ones_array_2d.shape)
print(ones_array_2d.size)
print(len(ones_array_2d))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
2
(4, 5)
20
4


In [96]:
ones_array_2d = np.ones((4, 5), dtype = 'int')
print(ones_array_2d)
print(ones_array_2d.ndim)
print(ones_array_2d.shape)
print(ones_array_2d.size)
print(len(ones_array_2d))

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
2
(4, 5)
20
4


<b>3. np.empty():</b>

<li>Return a new array of given shape and type, with random values.</li>
<li>Note : empty, unlike zeros, does not set the array values to zero, and may therefore be marginally faster.</li>
<li>It accepts three parameters. They are as follows:</li>
<ol>
    <li><b>shape:</b> Shape of the empty array, e.g., (2, 3) or 2.	Required</li>
    <li><b>dtype:</b> Desired output data-type for the array, e.g, numpy.int8. Default is numpy.float64.	optional</li>
    <li><b>order:</b> Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory. optional</li>
</ol>

In [97]:
empty_array1d = np.empty(5)
print(empty_array1d)
print(empty_array1d.size)
print(empty_array1d.ndim)
print(empty_array1d.shape)
print(len(empty_array1d))

[2.12199579e-314 6.36598737e-314 1.06099790e-313 1.48539705e-313
 1.90979621e-313]
5
1
(5,)
5


In [98]:
empty_array2d = np.empty((2, 3))
print(empty_array2d)
print(empty_array2d.size)
print(empty_array2d.ndim)
print(empty_array2d.shape)
print(len(empty_array2d))

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [1.95821982e-306 1.89146896e-307 7.56571288e-307]]
6
2
(2, 3)
2


In [100]:
empty_array2d = np.empty((2, 3),dtype = 'int', order = "C")
print(empty_array2d)
print(empty_array2d.size)
print(empty_array2d.ndim)
print(empty_array2d.shape)
print(len(empty_array2d))

[[  508737360         372   511467904]
 [        372           0 -2147483648]]
6
2
(2, 3)
2


In [101]:
empty_array2d = np.empty((2, 3),dtype = 'int', order = "F")
print(empty_array2d)
print(empty_array2d.size)
print(empty_array2d.ndim)
print(empty_array2d.shape)
print(len(empty_array2d))

[[  508737360           0           1]
 [        372           0 -2147483648]]
6
2
(2, 3)
2


<b>4. np.arange()</b>
<li>This arange() function is similar like range in Python.</li>
<li>np.arange() returns an array with evenly spaced elements as per the interval. The interval mentioned is half-opened i.e. [Start, Stop)</li>
<li>It accepts four parameters which are as follows:</li>
<ol>
    <li>start : [optional] start of interval range. By default start = 0</li>
    <li>stop  : end of interval range</li>
    <li>step  : [optional] step size of interval. By default step size = 1,</li>  
    <li>dtype : type of output array</li>
</ol>

In [103]:
arrange_array = np.arange(1,11)
print(arrange_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [104]:
arrange_array = np.arange(1,11, 3)
print(arrange_array)

[ 1  4  7 10]


In [105]:
arrange_array = np.arange(1,11, 3, 'float')
print(arrange_array)

[ 1.  4.  7. 10.]


<b>5.np.eye():</b>
<li>An array where diagonal element is filled with 1's.</li>
<li>It accepts four parameters which are as follows:</li>
<ol>
    <li>R: no of rows</li>
    <li>C: no of columns</li>
    <li>k : [int, optional, 0 by default]
          Diagonal we require; k>0 means diagonal above main diagonal or vice versa.</li>
    <li>dtype : [optional, float(by Default)] Data type of returned array.</li>


In [108]:
diagonal_matrix = np.eye(5,6,k = 1)
print(diagonal_matrix)

[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [113]:
diagonal_matrix_2 = np.eye(5,6,k = -4)
print(diagonal_matrix_2)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]


In [114]:
diagonal_matrix_3 = np.eye(5,6,k = -4, dtype = 'int')
print(diagonal_matrix_3)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]]


<b>6. np.linspace():</b> 
<li>It will create an array with values that are spaced linearly in a specified interval.</li>
<li>The numpy.linspace() function returns number spaces evenly w.r.t interval. Similar to numpy.arange() function but instead of step it uses sample number.</li>
<li>It accepts 5 parameters. They are as follows:</li>
<ol>
    <li>start  : [optional] start of interval range. By default start = 0</li>
    <li>stop   : end of interval range</li>
    <li>retstep : If True, return (samples, step). By default retstep = False</li>
    <li>num    : [int, optional] No. of samples to generate</li>
    <li>dtype  : type of output array</li>
</ol>

## Create Numpy Arrays With Random Numbers

<li>Earlier, we read about some special functions with which we can create special numpy arras.</li>
<li>If we want our numpy arrays to have random values, then this can be achived by utilizing four special functions which is capable for generating random values.</li>
<li>They are:</li>
<ol>
    <li>rand()</li>
    <li>randn()</li>
    <li>ranf()</li>
    <li>randint()</li>
</ol>

<b>1. rand():</b>
<li>The numpy.random.rand() function creates an array of specified shape and fills it with random values.</li>
<li>This function is used to generate a random value between 0 and 1.</li>

In [ ]:
np.random.rand(4)

<b>2. randn():</b>
<li>The numpy.random.randn() function creates an array of specified shape and fills it with random values as per standard normal distribution.</li>
<li>This function is used to generate a random value close to zero(0).</li>
<li>This function may return positive as well as negative numbers as well.</li>


<b>3.randf():</b>
<li>It returns an array of specified shape and fills it with random floats in the half open interval [0.0, 1.0)</li>

<b>4. randint()</b>
<li>This function is used to generate random numbers between a given range.</li>
<li>randint() is an inbuilt function of the random module in Python3.</li>
<li>It accepts two parameters. They are:</li>
<ol>
    <li>start: a starting point which is an integer value.</li>
    <li>end: an ending point which is also an integer value.</li>